export default {
	state: () => ({
		produtos: [
			{
				newhairvitamin: [
					{
						nomeProduto: "1 pote New Hair Ácido Hialurônico",
						nomeProdutoLp: "1 pote New Hair Ácido Hialurônico",
						subtituloProduto: "Vitaminas para cabelos, pele e unhas",
						img: "assets/img/produtos/nh-acido-hialuronico/loja/desk/New-Hair-Vitamina-Capilar-Acido-Hialuronico-Biotina.jpg",
						imgMob: "assets/img/produtos/nh-acido-hialuronico/loja/mob/New-Hair-Vitamina-Capilar-Acido-Hialuronico-Biotina.jpg",
						precoDe: 149.90,
						precoPor: 117.70,
						quantidadeProduto: 1,
						idProduto: 169,
						urlImgLp: "/vitamina-para-cabelo-e-unha-em-comprimido",
						urlBotaoSingle: "/vitamina-para-cabelo-com-acido-hialuronico-e-biotina.html",
						alt: "Uma embalagem de New Hair com tampa de alumínio e rótulo nas cores branco, rosa e preto, com a descrição do produto. Em destaque lemos: vitaminas - cabelos, pele e unhas",
						title: "1 pote New Hair Ácido Hialurônico - Comprimidos para cabelos, pele e unhas",
						urlLista: "/new-hair-vitamina-capilar-com-acido-hialuronico-e-biotina-1-pote.html",
					},
					{
						nomeProduto: "3 potes vitaminas com <br class='desk'> Ácido Hialurônico + Brinde",
						nomeProdutoLp: "3 potes New Hair Ácido Hialurônico",
						subtituloProduto: "Vitaminas para cabelos, pele e unhas",
						img: "assets/img/produtos/nh-acido-hialuronico/loja/desk/New-Hair-Vitamina-Capilar-Acido-Hialuronico-Biotina-3-Potes.jpg",
						imgMob: "assets/img/produtos/nh-acido-hialuronico/loja/mob/New-Hair-Vitamina-Capilar-Acido-Hialuronico-Biotina-3-Potes.jpg",
						precoDe: 449.70,
						precoPor: 227.70,
						quantidadeProduto: 3,
						idProduto: 177,
						urlImgLp: "/vitamina-para-cabelo-e-unha-em-comprimido",
						urlBotaoSingle: "/new-hair-vitamina-capilar-com-acido-hialuronico-e-biotina-3-potes.html",
						alt: "Três embalagens de New Hair com tampa de alumínio e rótulo nas cores branco, rosa e preto, com a descrição do produto. Em destaque lemos: vitaminas - cabelos, pele e unhas",
						title: "3 potes New Hair Ácido Hialurônico - Comprimidos para cabelos, pele e unhas",
						urlLista: "/new-hair-vitamina-capilar-com-acido-hialuronico-e-biotina-3-potes.html",
					},
					{
						nomeProduto: "6 potes New Hair Ácido Hialurônico + Brindes",
						nomeProdutoLp: "6 potes New Hair Ácido Hialurônico",
						subtituloProduto: "Vitaminas para cabelos, pele e unhas + Brinde",
						img: "assets/img/produtos/nh-acido-hialuronico/loja/desk/6-POTES-NEW-HAIR-ACIDO-HIALURONICO.jpg",
						imgMob: "assets/img/produtos/nh-acido-hialuronico/loja/mob/6-POTES-NEW-HAIR-ACIDO-HIALURONICO.jpg",
						precoDe: 899.40,
						precoPor: 397.70,
						quantidadeProduto: 6,
						idProduto: 178,
						urlImgLp: "/vitamina-para-cabelo-e-unha-em-comprimido",
						urlBotaoSingle: "/new-hair-vitamina-capilar-com-acido-hialuronico-e-biotina-7-potes.html",
						alt:"Seis embalagens de New Hair com tampa de alumínio e rótulo nas cores branco, rosa e preto, com a descrição do produto. Em destaque lemos: vitaminas - cabelos, pele e unhas",
						title: "New Hair Ácido Hialurônico - 6 potes + Brindes",
						urlLista: "/new-hair-vitamina-capilar-com-acido-hialuronico-e-biotina-7-potes.html",
					},
				],
				massageador: [
					{
						nomeProduto: "1 pote newhair vitamin",
						tituloProduto: "vitaminas, cabelos pele e unhas - newhair vitamin",
						nomeProdutoLp: "1 pote New Hair Ácido Hialurônico",
						subtituloProduto: "Vitaminas para cabelos, pele e unhas",
						tituloBrinde: "Ganhe Brinde",
						beneficios: [
							"Melhora da circulação sanguínea",
							"Relaxamento muscular",
							"Estímulo à produção de colágeno",
							"Melhora da absorção de produtos para a pele",
							"Redução de inchaço e olheiras",
						],
						galeria: [
							"assets/img/produtos/nh-acido-hialuronico/loja/desk/New-Hair-Vitamina-Capilar-Acido-Hialuronico-Biotina.jpg",
							"assets/img/produtos/nh-acido-hialuronico/loja/desk/New-Hair-Vitamina-Capilar-Acido-Hialuronico-Biotina.jpg",
							"assets/img/produtos/nh-acido-hialuronico/loja/desk/New-Hair-Vitamina-Capilar-Acido-Hialuronico-Biotina.jpg",
						],
						img: "assets/img/produtos/nh-acido-hialuronico/loja/desk/New-Hair-Vitamina-Capilar-Acido-Hialuronico-Biotina.jpg",
						imgMob: "assets/img/produtos/nh-acido-hialuronico/loja/mob/New-Hair-Vitamina-Capilar-Acido-Hialuronico-Biotina.jpg",
						precoDe: 149.90,
						precoPor: 117.70,
						quantidadeProduto: 1,
						exibirDesconto: false,
						idProduto: 169,
						urlImgLp: "/vitamina-para-cabelo-e-unha-em-comprimido",
						urlBotaoSingle: "/vitamina-para-cabelo-com-acido-hialuronico-e-biotina.html",
						alt: "Uma embalagem de New Hair com tampa de alumínio e rótulo nas cores branco, rosa e preto, com a descrição do produto. Em destaque lemos: vitaminas - cabelos, pele e unhas",
						title: "1 pote New Hair Ácido Hialurônico - Comprimidos para cabelos, pele e unhas",
						urlLista: "/vitamina-para-cabelo-com-acido-hialuronico-e-biotina.html",
					},
					{
						nomeProduto: "3 potes newhair vitaminaa",
						nomeProdutoLp: "3 potes New Hair Ácido Hialurônico",
						subtituloProduto: "Vitaminas para cabelos, pele e unhas",
						img: "assets/img/produtos/nh-acido-hialuronico/loja/desk/New-Hair-Vitamina-Capilar-Acido-Hialuronico-Biotina-3-Potes.jpg",
						imgMob: "assets/img/produtos/nh-acido-hialuronico/loja/mob/New-Hair-Vitamina-Capilar-Acido-Hialuronico-Biotina-3-Potes.jpg",
						precoDe: 449.70,
						precoPor: 227.70,
						quantidadeProduto: 3,
						exibirDesconto: true,
						exibirMaisVendido: true,
						idProduto: 177,
						urlImgLp: "/vitamina-para-cabelo-e-unha-em-comprimido",
						urlBotaoSingle: "/new-hair-vitamina-capilar-com-acido-hialuronico-e-biotina-3-potes.html",
						alt: "Três embalagens de New Hair com tampa de alumínio e rótulo nas cores branco, rosa e preto, com a descrição do produto. Em destaque lemos: vitaminas - cabelos, pele e unhas",
						title: "3 potes New Hair Ácido Hialurônico - Comprimidos para cabelos, pele e unhas",
						urlLista: "/new-hair-vitamina-capilar-com-acido-hialuronico-e-biotina-3-potes.html",
					},
					{
						nomeProduto: "6 potes newhair vitamin",
						nomeProdutoLp: "6 potes New Hair Ácido Hialurônico",
						subtituloProduto: "Vitaminas para cabelos, pele e unhas + Brinde",
						img: "assets/img/produtos/nh-acido-hialuronico/loja/desk/6-POTES-NEW-HAIR-ACIDO-HIALURONICO.jpg",
						imgMob: "assets/img/produtos/nh-acido-hialuronico/loja/mob/6-POTES-NEW-HAIR-ACIDO-HIALURONICO.jpg",
						precoDe: 899.40,
						precoPor: 397.70,
						quantidadeProduto: 6,
						exibirDesconto: true,
						idProduto: 178,
						urlImgLp: "/vitamina-para-cabelo-e-unha-em-comprimido",
						urlBotaoSingle: "/new-hair-vitamina-capilar-com-acido-hialuronico-e-biotina-7-potes.html",
						alt:"Seis embalagens de New Hair com tampa de alumínio e rótulo nas cores branco, rosa e preto, com a descrição do produto. Em destaque lemos: vitaminas - cabelos, pele e unhas",
						title: "New Hair Ácido Hialurônico - 6 potes + Brindes",
						urlLista: "/new-hair-vitamina-capilar-com-acido-hialuronico-e-biotina-7-potes.html",
					},
				],
				newhairvitaminbiotina: [
					{
						nomeProduto: "1 pote vitaminas <br> Para Mamãe",
						nomeProdutoLp: `1 pote New Hair<br class="mob"> Para Mamãe`,
						subtituloProduto: "Vitaminas e minerais essenciais",
						img: "assets/img/produtos/nh-biotina/loja/desk/New-Hair-Vitamina-Capilar-Biotina.jpg",
						imgMob: "assets/img/produtos/nh-biotina/loja/mob/New-Hair-Vitamina-Capilar-Biotina.jpg",
						precoDe: 149.90,
						precoPor: 117.70,
						quantidadeProduto: 1,
						idProduto: 179,
						urlImgLp: "/vitamina-para-gestante-e-lactantes",
						urlBotaoSingle: "/vitamina-para-cabelo-gestante-e-lactantes.html",
						alt: "Uma embalagem de New Hair com tampa de alumínio nas cores rosa, branco e preto, com a descrição do produto. Em destaque lemos: vitaminas - cabelos, pele e unhas",
						title: "New Hair Vitamina Capilar - 1 pote para mamães",
						urlLista: "/new-hair-vitamina-capilar-com-biotina-1-pote.html",
					},
					{
						nomeProduto: "3 potes vitaminas <br> Para Mamãe + Brinde",
						nomeProdutoLp: "3 potes New Hair Para Mamãe",
						subtituloProduto: "Vitaminas para gestantes e lactantes",
						img: "assets/img/produtos/nh-biotina/loja/desk/New-Hair-Vitamina-Capilar-Biotina-3-Potes.jpg",
						imgMob: "assets/img/produtos/nh-biotina/loja/mob/New-Hair-Vitamina-Capilar-Biotina-3-Potes.jpg",
						precoDe: 449.70,
						precoPor: 227.70,
						quantidadeProduto: 3,
						idProduto: 181,
						urlImgLp: "/vitamina-para-gestante-e-lactantes",
						urlBotaoSingle: "/new-hair-vitamina-capilar-com-biotina-3-potes.html",
						alt: "Três embalagens de New Hair com tampa de alumínio nas cores rosa, branco e preto, com a descrição do produto. Em destaque lemos: vitaminas - cabelos, pele e unhas",
						title: "New Hair Vitamina Capilar - 3 potes para mamães",
						urlLista: "/new-hair-vitamina-capilar-com-biotina-3-potes-1.html",
					},
					{
						nomeProduto: "6 potes New Hair <br>Para Mamãe + Brindes",
						nomeProdutoLp: "6 potes New Hair Para Mamãe",
						subtituloProduto: "Vitaminas para gestantes e lactantes + Brinde",
						img: "assets/img/produtos/nh-biotina/loja/desk/6-POTES-NEW-HAIR-BIOTINA.jpg",
						imgMob: "assets/img/produtos/nh-biotina/loja/mob/6-POTES-NEW-HAIR-BIOTINA.jpg",
						precoDe: 899.40,
						precoPor: 397.70,
						quantidadeProduto: 6,
						idProduto: 182,
						urlImgLp: "/vitamina-para-gestante-e-lactantes",
						urlBotaoSingle: "/new-hair-vitamina-capilar-com-biotina-7-potes.html",
						alt:"Seis embalagens de New Hair com tampa de alumínio nas cores rosa, branco e preto, com a descrição do produto. Em destaque lemos: vitaminas - cabelos, pele e unhas",
						title: "New Hair Vitamina Capilar - 6 potes + Brindes",
						urlLista: "/new-hair-vitamina-capilar-com-biotina-7-potes.html",
					},
				],
				serum: [
					{
						nomeProduto: "1 frasco Sérum Facial New Hair",
						nomeProdutoLp: `1 frasco Sérum Facial<br class="mob"> 10 em 1`,
						subtituloProduto: "10 ativos poderosos em um frasco só",
						img: "assets/img/produtos/nh-serum/loja/desk/new-hair-imagens-kit-1.jpg",
						imgMob: "assets/img/produtos/nh-serum/loja/mob/new-hair-imagens-kit-1.jpg",
						precoDe: 149.90,
						precoPor: 97.70,
						quantidadeProduto: 1,
						idProduto: 186,
						urlImgLp: "/serum-facial",
						urlBotaoSingle: "/serum-facial-10-em-1-new-hair.html",
						alt: "Uma embalagem do Sérum Facial New Hair com tampa branca nas cores rosa e branco, com a descrição do produto. Em destaque lemos: Sérum Facial dez em um",
						title: "Sérum Facial New Hair 10 em 1 - 1 frasco",
						urlLista: "/serum-facial-new-hair-10-em-1-1-frasco.html",
					},
					{
						nomeProduto: "2 frascos Sérum Facial New Hair",
						nomeProdutoLp: "2 frascos Sérum Facial 10 em 1",
						subtituloProduto: "Para descomplicar o skincare em casa",
						img: "assets/img/produtos/nh-serum/loja/desk/new-hair-imagens-kit2.jpg",
						imgMob: "assets/img/produtos/nh-serum/loja/mob/new-hair-imagens-kit2.jpg",
						precoDe: 299.80,
						precoPor: 167.70,
						quantidadeProduto: 2,
						idProduto: 187,
						urlImgLp: "/serum-facial",
						urlBotaoSingle: "/serum-facial-10-em-1-new-hair-2-frascos.html",
						alt: "Duas embalagens do Sérum Facial New Hair com tampa branca nas cores rosa e branco, com a descrição do produto. Em destaque lemos: Sérum Facial dez em um",
						title: "Sérum Facial 10 em 1 New Hair - 2 frascos",
						urlLista: "/serum-facial-new-hair-10-em-1-2-frasco.html",
					},
					{
						nomeProduto: "3 frascos Sérum Facial New Hair",
						nomeProdutoLp: "3 frascos Sérum Facial 10 em 1",
						subtituloProduto: "Skincare em minutos sem sair de casa",
						img: "assets/img/produtos/nh-serum/loja/desk/new-hair-imagens-ki3t.jpg",
						imgMob: "assets/img/produtos/nh-serum/loja/mob/new-hair-imagens-ki3t.jpg",
						precoDe: 449.70,
						precoPor: 197.70,
						quantidadeProduto: 3,
						idProduto: 188,
						urlImgLp: "/serum-facial",
						urlBotaoSingle: "/serum-facial-10-em-1-new-hair-3-frascos.html",
						alt: "Três embalagens do Sérum Facial New Hair com tampa branca nas cores rosa e branco, com a descrição do produto. Em destaque lemos: Sérum Facial dez em um",
						title: "Sérum Facial New Hair 10 em 1 - 3 frascos",
						urlLista: "/serum-facial-new-hair-10-em-1-3-frascos.html",
					},
				],
				linhaessential: [
					{
						nomeProduto: "Kit Completo Liso Perfeito",
						nomeProdutoLp: "Kit Completo Liso Perfeito",
						subtituloProduto: "",
						img: "assets/img/produtos/nh-linha-essential/loja/desk/liso-300x300.png",
						imgMob: "assets/img/produtos/nh-linha-essential/loja/mob/liso-300x300.png",
						precoDe: 149.99,
						precoPor: 108.56,
						quantidadeProduto: 1,
						idProduto: 186,
						urlImgLp: "/serum-facial",
						urlBotaoSingle: "/new-hair-home-care-essential-liso-perfeito.html",
						alt: "Imagem do Kit Completo Linha Essential Liso Perfeito com na cores rosa, branco e preto, contendo um shampoo, um condicionador um sérum e uma máscara capilar. Em destaque lemos: Linha Essential ",
						title: "Kit Completo Liso Perfeito",
						urlLista: "/serum-facial-new-hair-10-em-1-1-frasco.html",
					},
					{
						nomeProduto: "Kit Completo S.O.S Reparação",
						nomeProdutoLp: "Kit Completo S.O.S Reparação",
						subtituloProduto: "",
						img: "assets/img/produtos/nh-linha-essential/loja/desk/sos-reparaçaõ--300x300.png",
						imgMob: "assets/img/produtos/nh-linha-essential/loja/mob/sos-reparaçaõ--300x300.png",
						precoDe: 299.80,
						precoPor: 186.33,
						quantidadeProduto: 2,
						idProduto: 187,
						urlImgLp: "/serum-facial",
						urlBotaoSingle: "/new-hair-home-care-essential-sos-reparacao.html",
						alt:"Imagem do Kit Completo Linha Essential S.O.S. Reparação nas cores salmão, branco e preto, contendo um shampoo, um condicionador e uma máscara capilar. Em destaque lemos: Linha Essential",
						title: "Kit Completo S.O.S Reparação",
						urlLista: "/serum-facial-new-hair-10-em-1-2-frasco.html",
					},
					{
						nomeProduto: "Kit Completo Força e Brilho",
						nomeProdutoLp: "Kit Completo Força e Brilho",
						subtituloProduto: "Skincare em minutos sem sair de casa",
						img: "assets/img/produtos/nh-linha-essential/loja/desk/força-e-bilho-300x300.png",
						imgMob: "assets/img/produtos/nh-linha-essential/loja/desk/força-e-bilho-300x300.png",
						precoDe: 449.70,
						precoPor: 219.67,
						quantidadeProduto: 3,
						idProduto: 188,
						urlImgLp: "/serum-facial",
						urlBotaoSingle: "/new-hair-home-care-essential-forca-e-brilho.html",
						alt:"Imagem do Kit Completo Linha Essential Força e Brilho nas cores azul, branco e preto, contendo um shampoo, um condicionador, um sérum e uma máscara capilar. Em destaque lemos: Linha Essential",
						title: "Kit Completo Força e Brilho",
						urlLista: "/serum-facial-new-hair-10-em-1-3-frascos.html",
					},
				],
				gummy: [
					{
						nomeProduto: "1 pote New Hair Gummy",
						nomeProdutoLp: "1 pote New Hair Gummy",
						subtituloProduto: "Gomas para cabelos com Ácido Hialurônico",
						img: "assets/img/produtos/nh-gummy/loja/desk/1-POTE-NEW-HAIR-GOMA-MORANGO-FRESH.jpg",
						imgMob: "assets/img/produtos/nh-gummy/loja/mob/1-POTE-NEW-HAIR-GOMA-MORANGO-FRESH.jpg",
						// usar a variavel global $requestSend para puxar o valor do produto
						
						precoDe: 159.90,
						precoPor: 137.70,
						quantidadeProduto: 1,
						possuiVariacao: true,
						urlImgLp: "/new-hair-gummy-vitamina-em-goma-para-cabelo",
						urlBotaoSingle: "/new-hair-gummy-morango-vitamina-em-goma-para-cabelos-e-unhas.html",
						urlLista: "/new-hair-gummy-morango-vitamina-em-goma-para-cabelos-e-unhas-1-pote.html",
						variacoes:[
							{
								id:91, 
								nome:'Gummy Morango', 
								tipo:'lista',
								title: '1 Pote New Hair Gummy Morango',
								alt: 'Imagem do produto Gummy Morango'
							},
							{
								id:89,
								nome:'Gummy Uva', 
								tipo:'lista',
								alt: 'Gummy Uva',
								title: 'Imagem do produto Gummy Uva'
							},
							{
								id:87, 
								nome:'Gummy Laranja', 
								tipo:'lista',
								alt: 'Gummy Laranja',
								title: 'Imagem do produto Gummy Laranja'
							},
						],
					},
					{
						nomeProduto: "3 potes Gummy + Brinde",
						nomeProdutoLp: "3 potes New Hair Gummy",
						subtituloProduto: "Gomas para cabelos com Ácido Hialurônico",
						img: "assets/img/produtos/nh-gummy/loja/desk/3-POTES-NEW-HAIR-GOMA-MIX.jpg",
						imgMob: "assets/img/produtos/nh-gummy/loja/mob/3-POTES-NEW-HAIR-GOMA-MIX.jpg",
						precoDe: 479.90,
						precoPor: 267.70,
						quantidadeProduto: 3,
						possuiVariacao: true,
						urlImgLp: "/new-hair-gummy-vitamina-em-goma-para-cabelo",
						urlBotaoSingle: "/new-hair-gummy-vitamina-em-goma-para-cabelos-e-unhas-3-potes-4.html",
						urlLista: "/new-hair-gummy-laranja-uva-morango-vitamina-em-goma-para-cabelos-e-unhas.html",
						variacoes:[
							{
								id:94, 
								nome:'3 Potes Gummy Uva - Laranja - Morango', 
								tipo:'lista',
								alt: 'Imagem do produto 3 Potes Gummy Uva - Laranja - Morango',
								title: '3 Potes Gummy Uva - Laranja - Morango'
							},
							{
								id:93, 
								nome:'3 Potes - Morango',
								tipo:'lista',
								alt: '3 Potes - Morango',
								title: 'Imagem do produto 3 Potes - Morango'
							},
							{
								id:90, 
								nome:'3 Potes - Uva Verde', 
								tipo:'lista',
								alt: '3 Potes - Uva Verde',
								title: 'Imagem do produto 3 Potes - Uva Verde'
							},
							{
								id:88, 
								nome:'3 potes Gummy Laranja', 
								tipo:'lista',
								alt: '3 Potes - Laranja',
								title: 'Imagem do produto 3 potes Gummy Laranja'
							},
						],
					},
					{
						nomeProduto: "6 potes New Hair Gummy <br class='desk'> + Brindes",
						nomeProdutoLp: "6 potes New Hair Gummy + Brindes",
						subtituloProduto: "Gomas para cabelos com Ácido Hialurônico + Brinde",
						img: "assets/img/produtos/nh-gummy/loja/desk/6-POTES-NEW-HAIR-GOMA-MIX.jpg",
						imgMob: "assets/img/produtos/nh-gummy/loja/mob/6-POTES-NEW-HAIR-GOMA-MIX.jpg",
						precoDe: 959.40,
						precoPor: 467.70,
						quantidadeProduto: 6,
						possuiVariacao: true,
						urlImgLp: "/new-hair-gummy-vitamina-em-goma-para-cabelo",
						urlBotaoSingle: "/new-hair-gummy-vitamina-em-goma-para-cabelos-e-unhas-6-mais-1-potes.html",
						urlLista: "/new-hair-gummy-mix-3-morango-laranja-uva-7-potes.html",
						variacoes:[
							{
								id:170, 
								nome:'2 Potes Morango + 2 Uva + 2 Laranja', 
								tipo:'lista',
								alt:'Imagem dos produtos New Hair Gummy 2 Potes Morango + 2 Potes Uva + 2 Potes Laranja',
								title:'New Hair Gummy Kit 6 Potes - Vitamina para cabelos, pele e unhas'
							},
							{
								id:171, 
								nome:'6 Potes Morango', 
								tipo:'lista',
								alt:'Imagem dos produtos New Hair Gummy 6 potes Morango',
								title:'New Hair Gummy Kit 6 Potes Morango - Vitamina para cabelos, pele e unhas'
							},
							{
								id:172, 
								nome:'6 Potes Uva Verde', 
								tipo:'lista',
								alt:'Imagem dos produtos New Hair Gummy 6 potes Uva Verde',
								title:'New Hair Gummy Kit 6 Potes Uva Verde - Vitamina para cabelos, pele e unhas'

							},
							{
								id:173,
								nome:'6 Potes Laranja', 
								tipo:'lista',
								alt:'Imagem dos produtos New Hair Gummy 6 potes Laranja',
								title:'New Hair Gummy Kit 6 Potes Laranja - Vitamina para cabelos, pele e unhas'
							},
						],
					},
				],
				newhairvitaminmasculino: [
					{
						nomeProduto: "1 pote vitaminas Masculino",
						nomeProdutoLp: "New Hair Vitamin Masculino",
						subtituloProduto: "Para cabelos, pele e unhas",
						img: "assets/img/produtos/nh-masculino/loja/desk/New-Hair-Vitamina-Capilar-Masculino.jpg",
						imgMob: "assets/img/produtos/nh-masculino/loja/mob/New-Hair-Vitamina-Capilar-Masculino.jpg",
						precoDe: 149.90,
						precoPor: 117.70,
						quantidadeProduto: 1,
						idProduto: 183,
						urlImgLp: "/new-hair-vitamina-em-goma-para-cabelo-e-barba-masculina",
						urlBotaoSingle: "/new-hair-vitamina-capilar-com-acido-hialuronicoebiotina-masculino.html",
						alt: "Imagem do produto New Hair Vitamin Masculino",
						title: "New Hair Vitamin Masculino - Para barba, cabelos e pele",
						urlLista: "/new-hair-vitamina-capilar-com-acido-hialuronico-e-biotina-masculino-1-pote.html",
					},
					{
						nomeProduto: "3 potes vitaminas Masculino",
						nomeProdutoLp: "3 potes New Hair Masculino",
						subtituloProduto: "Tratamento 90 dias",
						img: "assets/img/produtos/nh-masculino/loja/desk/New-Hair-Vitamina-Capilar-Masculino-3-Potes.jpg",
						imgMob: "assets/img/produtos/nh-masculino/loja/mob/New-Hair-Vitamina-Capilar-Masculino-3-Potes.jpg",
						precoDe: 449.70,
						precoPor: 227.70,
						quantidadeProduto: 3,
						idProduto: 184,
						urlImgLp: "/new-hair-vitamina-em-goma-para-cabelo-e-barba-masculina",
						urlBotaoSingle: "/new-hair-vitamina-capilar-com-acido-hialuronico-e-biotina-masculino-3-potes.html",
						alt: "Imagem do produto New Hair Vitamin Masculino - 3 potes",
						title: "3 Potes New Hair Vitamin Masculino - Para barba, cabelos e pele - Tratamento 90 dias",
						urlLista: "/new-hair-vitamina-capilar-com-acido-hialuronico-e-biotina-masculino-3-potes.html",
					},
					{
						nomeProduto: "6 potes New Hair Masculino + Brinde",
						nomeProdutoLp: "6 potes New Hair Ácido Hialurônico",
						subtituloProduto: "Tratamento 210 dias",
						img: "assets/img/produtos/nh-masculino/loja/desk/6-POTES-NEW-HAIR-MASCULINO.jpg",
						imgMob: "assets/img/produtos/nh-masculino/loja/mob/6-POTES-NEW-HAIR-MASCULINO.jpg",
						precoDe: 899.40,
						precoPor: 397.70,
						quantidadeProduto: 6,
						idProduto: 185,
						urlImgLp: "/new-hair-vitamina-em-goma-para-cabelo-e-barba-masculina",
						urlBotaoSingle: "/new-hair-vitamina-capilar-com-acido-hialuronico-e-biotina-masculino-7-potes.html",
						alt: "Imagem do produto New Hair Vitamin Masculino (6 potes)",
						title: "6 Potes New Hair Vitamin Masculino - Para barba, cabelos e pele - Tratamento 210 dias",
						urlLista: "/new-hair-vitamina-capilar-com-acido-hialuronico-e-biotina-masculino-7-potes.html",
					},
				],
				newhairgummymasculino: [
					{
						nomeProduto: "1 pote New Hair Gummy",
						nomeProdutoLp: "New Hair Gummy Masculino",
						subtituloProduto: "Para cabelos, pele e unhas",
						img: "assets/img/produtos/nh-gummy-masculino/loja/desk/1-POTE-NEW-HAIR-GOMA-MASCULINO.jpg",
						imgMob: "assets/img/produtos/nh-gummy-masculino/loja/mob/1-POTE-NEW-HAIR-GOMA-MASCULINO.jpg",
						precoDe: 149.90,
						precoPor: 137.70,
						quantidadeProduto: 1,
						idProduto: 108,
						urlImgLp: "/new-hair-vitamina-em-goma-para-cabelo-e-barba-masculina",
						urlBotaoSingle: "/new-hair-gummy-uva-verde-vitamina-em-goma-para-cabelos.html",
						alt: "Imagem do produto 1 pote New Hair Gummy Masculino",
						title: "1 pote New Hair Gummy Masculino - Para cabelos, pele e unhas",
						urlLista: "/new-hair-gummy-uva-verde-vitamina-em-goma-para-cabelos-e-unhas-1-pote-masculino.html",
					},
					{
						nomeProduto: "3 potes New Hair Gummy",
						nomeProdutoLp: "3 potes Gummy Masculino",
						subtituloProduto: "Tratamento 90 dias",
						img: "assets/img/produtos/nh-gummy-masculino/loja/desk/3-POTES-NEW-HAIR-GOMA-MASCULINO.jpg",
						imgMob: "assets/img/produtos/nh-gummy-masculino/loja/mob/3-POTES-NEW-HAIR-GOMA-MASCULINO.jpg",
						precoDe: 449.70,
						precoPor: 267.70,
						quantidadeProduto: 3,
						idProduto: 109,
						urlImgLp: "/new-hair-vitamina-em-goma-para-cabelo-e-barba-masculina",
						urlBotaoSingle: "/new-hair-gummy-uva-verde-vitamina-em-goma-para-cabelos.html",
						alt: "Imagem do produto 3 potes New Hair Gummy Masculino",
						title: "3 potes New Hair Gummy Masculino - Tratamento 90 dias",
						urlLista: "/new-hair-gummy-uva-verde-vitamina-em-goma-para-cabelos-e-unhas-3-potes-masculino.html",
					},
					{
						nomeProduto: "6 potes New Hair Gummy + Brinde",
						nomeProdutoLp: "6 potes New Hair Gummy + Brinde",
						subtituloProduto: "Tratamento 210 dias",
						img: "assets/img/produtos/nh-gummy-masculino/loja/desk/6-POTES-NEW-HAIR-GOMA-MASCULINO.jpg",
						imgMob: "assets/img/produtos/nh-gummy-masculino/loja/mob/6-POTES-NEW-HAIR-GOMA-MASCULINO.jpg",
						precoDe: 899.40,
						precoPor: 467.70,
						quantidadeProduto: 6,
						idProduto: 110,
						urlImgLp: "/new-hair-vitamina-em-goma-para-cabelo-e-barba-masculina",
						urlBotaoSingle: "/new-hair-gummy-uva-verde-vitamina-em-goma-para-cabelos.html",
						alt: "Imagem do produto 6 potes New Hair Gummy Masculino + Brinde",
						title: "6 potes New Hair Gummy Masculino + Brinde - Tratamento 210 dias",
						urlLista: "/new-hair-gummy-uva-verde-vitamina-em-goma-para-cabelos-e-unhas-6-potes-masculino.html",
					},
				],
			},
		],
	}),
};
